# Default values for helloworld-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 80

deployment:
  replicaCount: 1
  container: 
      image: "prasanna78/helloworld-app"
      tag: "1.0.0"
      imagePullPolicy: IfNotPresent
      port: 3000

ingress:
  className: "nginx-example"
  annotations: {}
  hosts:
      path: /hello
      pathType: Prefix
  service:
     port: 80




nodeSelector: {}

tolerations: []

affinity: {}
