apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloworld-app.fullname" . }}
  labels:
    {{- include "helloworld-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "helloworld-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helloworld-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.container.image }}:{{ .Values.deployment.container.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.container.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.deployment.container.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.deployment.container.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
