apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  labels:
    {{- include "helloworld-app.labels" . | nindent 4 }}
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.hosts.path }}
            pathType: {{ .Values.ingress.hosts.pathType }}
            backend:
              service:
                name: {{ include "helloworld-app.fullname" . }}
                port:
                  number: {{ .Values.ingress.service.port }}

